name: iRAG
channels:
  - conda-forge
  - nvidia/label/cuda-11.8.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.2.25
  - cuda-cccl=11.8.89
  - cuda-command-line-tools=11.8.0
  - cuda-compiler=11.8.0
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cuobjdump=11.8.86
  - cuda-cupti=11.8.87
  - cuda-cuxxfilt=11.8.86
  - cuda-documentation=11.8.86
  - cuda-driver-dev=11.8.89
  - cuda-gdb=11.8.86
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-memcheck=11.8.86
  - cuda-nsight=11.8.86
  - cuda-nsight-compute=11.8.0
  - cuda-nvcc=11.8.89
  - cuda-nvdisasm=11.8.86
  - cuda-nvml-dev=11.8.86
  - cuda-nvprof=11.8.87
  - cuda-nvprune=11.8.86
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-nvvp=11.8.87
  - cuda-profiler-api=11.8.86
  - cuda-sanitizer-api=11.8.86
  - cuda-toolkit=11.8.0
  - cuda-tools=11.8.0
  - cuda-visual-tools=11.8.0
  - cudatoolkit=11.7.0
  - cudatoolkit-dev=11.7.0
  - gds-tools=1.4.0.31
  - ld_impl_linux-64=2.40
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcufile=1.4.0.31
  - libcufile-dev=1.4.0.31
  - libcurand=10.3.0.86
  - libcurand-dev=10.3.0.86
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - nsight-compute=2022.3.0.22
  - openssl=3.0.16
  - pip=24.2
  - python=3.8.20
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
    - absl-py==2.2.2
    - accelerate==1.0.1
    - addict==2.4.0
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.4.4
    - aiohttp==3.10.11
    - aiosignal==1.3.1
    - altair==5.4.1
    - annotated-types==0.7.0
    - anyio==4.5.2
    - async-timeout==5.0.1
    - attrs==25.3.0
    - basicsr==1.4.2
    - bitsandbytes==0.41.1
    - braceexpand==0.1.7
    - cachetools==5.5.2
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - click==8.1.8
    - cmake==3.31.6
    - contourpy==1.1.1
    - cycler==0.12.1
    - deepspeed==0.16.7
    - diffusers==0.29.2
    - einops==0.8.1
    - exceptiongroup==1.2.2
    - fairscale==0.4.13
    - fastapi==0.115.11
    - ffmpy==0.5.0
    - filelock==3.16.1
    - fonttools==4.56.0
    - frozenlist==1.5.0
    - fsspec==2025.3.0
    - ftfy==6.2.3
    - future==1.0.0
    - google-auth==2.40.1
    - google-auth-oauthlib==1.0.0
    - gradio==3.24.0
    - gradio-client==1.1.0
    - grpcio==1.70.0
    - h11==0.14.0
    - hf-xet==1.1.0
    - hjson==3.1.0
    - httpcore==1.0.7
    - httpx==0.28.1
    - huggingface-hub==0.31.1
    - idna==3.10
    - imageio==2.35.1
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - jinja2==3.1.6
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.7
    - lazy-loader==0.4
    - lightning-utilities==0.11.9
    - linkify-it-py==2.0.3
    - lit==18.1.8
    - lmdb==1.6.2
    - loralib==0.1.2
    - markdown==3.7
    - markdown-it-py==2.2.0
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mpmath==1.3.0
    - msgpack==1.1.0
    - multidict==6.1.0
    - narwhals==1.31.0
    - networkx==3.1
    - ninja==1.11.1.4
    - numpy==1.24.4
    - nvidia-cublas-cu11==11.11.3.6
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.8.87
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.8.89
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.8.89
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.7.0.84
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.3.0.86
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.1.48
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.5.86
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-ml-py==12.575.51
    - nvidia-nccl-cu11==2.19.3
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.9.41
    - nvidia-nvtx-cu11==11.8.86
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - open-clip-torch==2.32.0
    - opencv-python==4.11.0.86
    - orjson==3.10.15
    - packaging==24.2
    - pandas==2.0.3
    - pillow==10.4.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - propcache==0.2.0
    - protobuf==5.29.4
    - psutil==7.0.0
    - py-cpuinfo==9.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.2
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pydub==0.25.1
    - pyparsing==3.1.4
    - python-dateutil==2.9.0.post0
    - python-multipart==0.0.20
    - pytorch-lightning==2.3.3
    - pytz==2025.1
    - pywavelets==1.4.1
    - pyyaml==6.0.2
    - referencing==0.35.1
    - regex==2024.11.6
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - rpds-py==0.20.1
    - rsa==4.9.1
    - safetensors==0.5.3
    - scikit-image==0.21.0
    - scipy==1.10.1
    - seaborn==0.13.2
    - semantic-version==2.10.0
    - six==1.17.0
    - sniffio==1.3.1
    - starlette==0.44.0
    - sympy==1.13.3
    - tb-nightly==2.14.0a20230808
    - tensorboard-data-server==0.7.2
    - tifffile==2023.7.10
    - timm==1.0.15
    - tokenizers==0.20.3
    - tomli==2.2.1
    - torch==2.2.1+cu118
    - torchaudio==2.2.1+cu118
    - torchmetrics==1.5.2
    - torchvision==0.17.1+cu118
    - tqdm==4.67.1
    - transformers==4.46.3
    - triton==2.2.0
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - uc-micro-py==1.0.3
    - ultralytics==8.3.129
    - ultralytics-thop==2.0.14
    - urllib3==2.2.3
    - uvicorn==0.33.0
    - wcwidth==0.2.13
    - webdataset==0.2.100
    - websockets==11.0.3
    - werkzeug==3.0.6
    - xformers==0.0.25
    - yapf==0.43.0
    - yarl==1.15.2
    - zipp==3.20.2
